/**
 * YouTube and external services error codes
 */

export const YOUTUBE_ERROR_CODES = {
    YOUTUBE_VIDEO_NOT_FOUND: 'ERR_YOUTUBE_VIDEO_NOT_FOUND',
    YOUTUBE_PLAYLIST_NOT_FOUND: 'ERR_YOUTUBE_PLAYLIST_NOT_FOUND',
    YOUTUBE_QUOTA_EXCEEDED: 'ERR_YOUTUBE_QUOTA_EXCEEDED',
    YOUTUBE_SERVICE_UNAVAILABLE: 'ERR_YOUTUBE_SERVICE_UNAVAILABLE',
} as const

export type YouTubeErrorCode =
    (typeof YOUTUBE_ERROR_CODES)[keyof typeof YOUTUBE_ERROR_CODES]
