/**
 * Discord bot error codes
 */

export const DISCORD_ERROR_CODES = {
    DISCORD_VOICE_CONNECTION_FAILED: 'ERR_DISCORD_VOICE_CONNECTION_FAILED',
    DISCORD_PERMISSION_MISSING: 'ERR_DISCORD_PERMISSION_MISSING',
    DISCORD_GUILD_NOT_FOUND: 'ERR_DISCORD_GUILD_NOT_FOUND',
    DISCORD_CHANNEL_NOT_FOUND: 'ERR_DISCORD_CHANNEL_NOT_FOUND',
} as const

export type DiscordErrorCode =
    (typeof DISCORD_ERROR_CODES)[keyof typeof DISCORD_ERROR_CODES]
